### ISSUE TITLE
Visual Validation Methods

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#398]
Support the validation of Super Resolution Restoration by providing visual analysis tools.

**Tasks**

- [ ] Collect criteria for “appealing” and “immersive” visual appearance of enhanced 3D models
- [ ] Adapt data presentation means, - qualitative, visual comparison of 3D data products
- [ ] Consider quantitative assessment, e.g. by mesh and texture comparisons (Schmidt et al., 2014) or PRo3D’s surface comparison from HERA project.
