### ISSUE TITLE
Co-registration Tool

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#400]
Provide tools to transform surfaces and textures to co-register them manually. 

**Tasks**

- [ ] Improve UI for numeric transformations
- [ ] Allow the definition of three++ corresponding 3D point pairs on respective 2 surfaces, and calculate Helmert transform to co-register Surface1. JR will provide a library same as for SPICE. Data interface is a corresponding point list, input for PRo3D is helmert transform with or without scaling adaptation
- [ ] Adapt existing 3D and 2D co-registration processes to refine mosaic pointing - use https://github.com/pro3d-space/PRo3D/issues/409  for the functionality
  - [ ] JR will provide a library same as for SPICE - the data interface is an ROI (obj or similar textured mesh) to be cut out from both surfaces. Textured ICP as option
- [ ] Incorporate PRo3D co-registration steps into the PRoViP pipeline --> allow export and import of transforms of selected surfaces

This is related to #478.

**Comment by ThomasOrtner** [comment]
this is issue has been addressed in the form of jupyter notebooks and is available in the current development branch since PR https://github.com/pro3d-space/PRo3D/pull/499

how this works is documented at https://github.com/pro3d-space/PRo3D/wiki/Interactive-Co%E2%80%90Registration-Workflow

Questions is, is there a GUI and a full user workflow needed? School interns successfully co-registered a large number of multiview AI validation candidates over this summer using the notebook implementation.

**Comment by chris-traxler** [comment]
Do enable compatibility with the co-registration workflow, a transform import for surfaces will be realised. This is then related to issue #315 and a first solution for this issue.
Trafos must be in the correct format.
