### ISSUE TITLE
Single Image to Surface Projection

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#405]
This shall realize the already drafted oriented shot capability.
It should be possible to project a selected or loaded image onto the selected surface(s). The projection is defined by the current viewpoint and direction or by a view of the View Planner. This helps to validate the reconstruction and assess its accuracy. On the other hand, by projecting rover images onto HiRise DTMs more details can be studied because of the higher texture resolution. This is helpful as long as no reconstructions from rover imagery is available.

**Tasks**

- [ ] Extend UI to load images and select them from a list
- [ ] Extend UI to configure and execute projection (i.e. from current view point or View Planner)
- [ ] Implement projection methods
- [ ] Extend multi-texturing to include these projections as separate 3D GIS layer

**Comment by haraldsteinlechner** [comment]
Is there a particular set of test images to be used for testing? 
PS.: yes, of course i will use artificial data for now, but for demonstration and user-manual a real test image would be beneficial

**Comment by chris-traxler** [comment]
Obsolete, because addressed in HERA project.
Currently only available in the HERA branch.
