### ISSUE TITLE
RIMFAX Subsurface Visualization

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#407]
Visualisation of RIMFAX ground penetrating radar (GPR) data in form of subsurface curtains. PRo3D should allow to explore and analyse this data in its geospatial context.

Detailed requirements will be defined together with the RIMFAX team and this issue will be adapted accordingly.

**Tasks**

- [ ] Extend UI to import RIMFAX trajectory (similar to rover trajectories)
- [ ] Visualisation of the RIMFAX trajectory in a similar way as the rover path
- [ ] Extend UI to import RIMFAX subsurface curtains as additional OPC and/or .gltf and/or .obj file
- [ ] Allow treatment of RIMFAX subsurface curtain by all existing surface operations modes (e.g. transform, colour modification, scaling, priority rendering, visibility, navigation to element, component of sequenced bookmarks, etc.)
- [ ] Allow annotations and measurements on RIMFAX subsurface curtain as available for all regular surface models.
- [ ] Foresee meta data treatment / display for RIMFAX as far as available (assignment of sol, processing history, statistics, …)
- [ ] Realize comprehensive rendering modes, e.g. by cutting the HiRISE & Mastcam-Z surfaces along the RIMFAX trajectory to see the subsurface GPR curtain
- [ ] Experiment with surface transparencies to allow a see-through experience

**Comment by chris-traxler** [comment]
If we take the OBJ approach, can we make sure that their textures are limited to 16k?
