### ISSUE TITLE
Rover Model

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#408]
Improve the PRo3D feature to import and place rover models.

**Tasks**

- [ ] Prepare a Perseverance rover model, e.g. from https://github.com/nasa-jpl/m2020-urdf-models/tree/main/rover for import into PRo3D
- [ ] Besides placing it on an arbitrary position it should be possible to place it on a waypoint of a rover traverse (including RIMFAX paths)
- [ ] If the rover pose is available from SPICE or other sources for a waypoint, set it into the correct pose

**Comment by chris-traxler** [comment]
Clarify with Gerhard current functionality and open features.
